services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jonston\SymfonyPermission\Repository\:
    resource: '../../Repository/*'
    tags: ['doctrine.repository_service']

  Jonston\SymfonyPermission\Service\:
    resource: '../../Service/*'
    exclude: '../../Service/*Interface.php'

  # Explicit service definitions
  Jonston\SymfonyPermission\Service\PermissionServiceInterface:
    alias: Jonston\SymfonyPermission\Service\PermissionService

  Jonston\SymfonyPermission\Service\RoleServiceInterface:
    alias: Jonston\SymfonyPermission\Service\RoleService
