services:
  _defaults:
    autowire: true
    autoconfigure: true

  Jonston\SymfonyPermission\:
    resource: '../'
    exclude:
      - '../Entity/'
      - '../Tests/'

  Jonston\SymfonyPermission\Service\PermissionService:
    public: true

  Jonston\SymfonyPermission\Service\RoleService:
    public: true

  Jonston\SymfonyPermission\Repository\PermissionRepository:
    tags: ['doctrine.repository_service']

  Jonston\SymfonyPermission\Repository\RoleRepository:
    tags: ['doctrine.repository_service']
